name: CI

on: [push, pull_request]

jobs:
  build:
    name: ubuntu:22.04-release
    runs-on: ubuntu-22.04
    env:
      CMAKE_GENERATOR: Ninja
      DEBIAN_FRONTEND: noninteractive
    steps:
      - name: install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            clang-format \
            cmake \
            ninja-build
      - name: checkout repository
        uses: actions/checkout@v4
      - name: compile
        run: |
          cmake -B build -S .
